.TH Service DAC "May, 2020" "version 0.1" "Permission control service"
.SH NAME
Service DAC \- Discretionary Access Control service
.SH DESCRIPTION
This is a service that monitors the access rights of the most
important system configuration files once a minute. If access
rights are rejected, the service changes the access rights to
standard ones. The list of files to monitor is controlled by
the administrator via a configuration file in the /etc
directory, containing the path to the file, access rights,
and owner/owner group.
.SH FILES
/opt/control_service/control_service.sh - examined files
.SH AUTHORS
Georgy Bychkov,
Daniil Evseenkov,
Darya Ivanova,
Sergey Kazmin,
Anton Savchenko
